## Neuron Implementation

In [1]:
import torch
import torch.nn as nn

In [2]:
# input 

torch.manual_seed(42)
inputs = torch.tensor([1.0, 2.0, 3.0])    #(x1, x2, x3) --> 1D array/Vector , Tensors are multidimensional Array


#### 0Dim = Sclar (consta val)
#### 1Dim = vector
#### 2Dim = matrix
#### 3Dim and more = tensor

In [3]:
neuron = nn.Linear(in_features=3, out_features=1)

In [4]:
output = neuron(inputs)

In [5]:
output

tensor([1.5244], grad_fn=<ViewBackward0>)

In [6]:
# To verify the Output -- formula
# Weighter Sum = Summation(XiWi + b)

neuron.weight @ inputs + neuron.bias      # @ --> multiplication

tensor([1.5244], grad_fn=<AddBackward0>)

In [7]:
neuron.weight

Parameter containing:
tensor([[ 0.4414,  0.4792, -0.1353]], requires_grad=True)

In [8]:
neuron.bias

Parameter containing:
tensor([0.5304], requires_grad=True)